services:
  - name: your-app
    runtime: python
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:app --bind 0.0.0.0:$PORT --timeout 200
